CREATE SCHEMA pizza;
GRANT ALL PRIVILEGES ON pizza.* TO 'pizza'@'localhost'
IDENTIFIED BY 'piz009asdfasdfasdfGGGGGG';
CREATE TABLE pizza.address (
  id                         INT PRIMARY KEY AUTO_INCREMENT,
  house_number               VARCHAR(255),
  street                     VARCHAR(255),
  city                       VARCHAR(255),
  state                      VARCHAR(255),
  postal_code                VARCHAR(255),
  subdivision                VARCHAR(255),
  closest_major_intersection VARCHAR(255),
  delivery_notes             VARCHAR(2000)
);
CREATE TABLE pizza.customer (
  id           INT PRIMARY KEY AUTO_INCREMENT,
  first_name   VARCHAR(255),
  last_name    VARCHAR(255),
  phone_number VARCHAR(255)
  card_type    VARCHAR(255),
  address_id   INT,
  INDEX address_index (address_id),
  FOREIGN KEY (address_id) REFERENCES address (id)
    ON DELETE CASCADE
);
CREATE TABLE pizza.customer_order (
  id             INT PRIMARY KEY AUTO_INCREMENT,
  customer_id    INT,
  payment_method VARCHAR(255),
  amount         DECIMAL(19, 4),
  notes          VARCHAR(2000),
  time           DATETIME,
  INDEX customer_index (customer_id),
  FOREIGN KEY (customer_id) REFERENCES customer (id)
);

CREATE TABLE pizza.menu_item (
  id     INT PRIMARY KEY AUTO_INCREMENT,
  name   VARCHAR(255),
  amount DECIMAL(19, 4)
);
CREATE TABLE pizza.menu_add_on (
  id     INT PRIMARY KEY AUTO_INCREMENT,
  name   VARCHAR(255),
  amount DECIMAL(19, 4)
);

CREATE TABLE pizza.menu_item_available_add_on (
  id             INT PRIMARY KEY AUTO_INCREMENT,
  menu_item_id   INT,
  menu_add_on_id INT,
  INDEX menu_item_index (menu_item_id),
  INDEX menu_add_on_index (menu_add_on_id),
  FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
  FOREIGN KEY (menu_add_on_id) REFERENCES menu_add_on (id)
);

CREATE TABLE pizza.order_item (
  id           INT PRIMARY KEY AUTO_INCREMENT,
  menu_item_id INT,
  quantity     INT,
  INDEX menu_item_index (menu_item_id),
  FOREIGN KEY (menu_item_id) REFERENCES menu_item (id)
);

CREATE TABLE pizza.order_item_add_on (
  id             INT PRIMARY KEY AUTO_INCREMENT,
  order_item_id  INT,
  menu_add_on_id INT,
  INDEX order_item (order_item_id),
  INDEX menu_add_on_index (menu_add_on_id),
  FOREIGN KEY (order_item_id) REFERENCES order_item (id),
  FOREIGN KEY (menu_add_on_id) REFERENCES menu_add_on (id)
);

CREATE TABLE pizza.customer_order_item (
  id                INT PRIMARY KEY AUTO_INCREMENT,
  customer_order_id INT,
  order_item_id     INT,
  INDEX customer_order_index (customer_order_id),
  INDEX order_item_index (order_item_id),
  FOREIGN KEY (customer_order_id) REFERENCES customer_order (id),
  FOREIGN KEY (order_item_id) REFERENCES order_item (id)
);

INSERT INTO pizza.address (house_number, street, city, state, postal_code, subdivision, closest_major_intersection, delivery_notes)
VALUES
  ('55', 'Texas St. NE', 'Kennesaw', 'GA', '30144', 'Darby Downs', 'Frey Rd. and Busbee Pkwy.',
   'knock quietly (their baby might be napping)'),
  ('9', 'Main St. NW, Unit # 2', 'Kennesaw', 'GA', '30144', 'Kennesaw Commons', 'Church St. and Main St.',
   'there are four units, this one is on the second story, entrance on the side facing the road'),
  ('1702', 'Mulberry Dr', 'Kennesaw', 'GA', '30144', 'Mathis Retirement Community', 'Church St. and Cherokee St.',
   'blue house, only ring door bell once, customer sometimes takes a couple minutes to answer the door');

INSERT INTO pizza.customer (first_name, last_name, phone_number, card_type, address_id) VALUES
  ('Charlie', 'Smith', '(770) 823-0912', 'Visa', 1),
  ('Pat', 'Smith', '(770) 823-0913', 'Visa', 1),
  ('Chris', 'Peterson', '(770) 362-3218', 'Master Card', 2),
  ('Jo', 'Peterson', '(770) 823-3329', 'Master Card', 2),
  ('Robert', 'Po', '(770) 129-0912', 'None', 3);

INSERT INTO pizza.customer_order (customer_id, payment_method, amount, notes, time) VALUES
  (1, 'Credit Card - Visa', 19.09, 'One large supreme pizza, and a 2 liter coke', NOW()),
  (1, 'Credit Card - Visa', 34.12, 'One large supreme pizza, one medium pepperoni, and a 2 liter coke',
   NOW()),
  (2, 'Credit Card - Visa', 19.09, 'One large supreme pizza, and a 2 liter coke', NOW()),
  (3, 'Credit Card - Master Card', 3.02, 'One large sweet tea', NOW()),
  (4, 'Credit Card - Master Card', 90.02, '10 large cheese pizza, one apple pie', NOW()),
  (5, 'Cash', 9.19, '1 small pizza with only cheese, olives, anchovies, and NO marinara', NOW()),
  (5, 'Cash', 9.19, '1 small pizza with only cheese, olives, anchovies, and NO marinara', NOW()),
  (5, 'Check', 9.19, '1 small pizza with only cheese, olives, anchovies, and NO marinara', NOW());

INSERT INTO pizza.menu_item (name, amount) VALUES
  ('Pizza - Small', 8.50),
  ('Pizza - Medium', 12.50),
  ('Pizza - Large', 16.50),
  ('Thin Crust Pizza - Small', 7.50),
  ('Thin Crust Pizza - Medium', 11.50),
  ('Thin Crust Pizza - Large', 15.50),
  ('Deep Dish Pizza - Small', 10.00),
  ('Deep Dish Pizza - Medium', 14.00),
  ('Deep Dish Pizza - Large', 18.00),
  ('Salad', 5.00),
  ('Soda', 2.00),
  ('Water', 0.00),
  ('Beer', 4.00),
  ('Wine', 5.00),
  ('Slice of Apple Pie', 3.00),
  ('Peanut Butter Brownie', 3.00);

/* Toppings as regular menu items since the add_on feature is not implemented */
INSERT INTO pizza.menu_item (name, amount) VALUES
  ('Topping: Pepperoni', 1.00),
    ('Topping: Anchovies', 1.00),
    ('Topping: Extra Cheese', 1.00),
    ('Topping: Meatballs', 2.00),
    ('Topping: Onions', 1.00),
    ('Topping: Italian Sausage', 2.00),
    ('Topping: Black Olives', 1.00),
    ('Topping: Green Olives', 1.00),
    ('Topping: Hot Peppers', 1.00),
    ('Topping: Feta Cheese', 1.00),
    ('Topping: Fresh Spinach', 1.00),
    ('Topping: Ham', 1.00),
    ('Topping: Pineapple', 1.00),
    ('Topping: Tomatoes', 1.00),
    ('Topping: Ricotta Cheese', 1.00),
    ('Topping: Gluten Free', 3.00),
    ('Topping: Ranch Dressing', 0.50),
    ('Topping: No Cheese', 0.00),
    ('Topping: No Sauce', 0.00),
    ('Topping: No Sauce', 0.00),
    ('Topping: Ranch Dressing', 0.50);

INSERT INTO pizza.menu_add_on (name, amount) VALUES
  ('Pepperoni', 1.00),
  ('Anchovies', 1.00),
  ('Extra Cheese', 1.00),
  ('Meatballs', 2.00),
  ('Onions', 1.00),
  ('Italian Sausage', 2.00),
  ('Black Olives', 1.00),
  ('Green Olives', 1.00),
  ('Hot Peppers', 1.00),
  ('Feta Cheese', 1.00),
  ('Fresh Spinach', 1.00),
  ('Ham', 1.00),
  ('Pineapple', 1.00),
  ('Tomatoes', 1.00),
  ('Ricotta Cheese', 1.00),
  ('No Marinara', 0.00),
  ('Gluten Free', 3.00),
  ('Ranch Dressing', 0.00),
  ('Italian Dressing', 0.00),
  ('Oil and Vinegar Dressing', 0.00),
  ('French Dressing', 0.00),
  ('Ice Cream', 2.00),
  ('Artisan Soda', 2.00),
  ('Premium Beer', 3.00),
  ('Premium Wine', 4.00);

  INSERT INTO menu_item_available_add_on (menu_item_id, menu_add_on_id) VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10),
    (1, 11),
    (1, 12),
    (1, 13),
    (1, 14),
    (1, 15),
    (1, 16),
    (1, 17),
    (1, 18),
    (2, 1),
    (2, 2),
    (2, 3),
    (2, 4),
    (2, 5),
    (2, 6),
    (2, 7),
    (2, 8),
    (2, 9),
    (2, 10),
    (2, 11),
    (2, 12),
    (2, 13),
    (2, 14),
    (2, 15),
    (2, 16),
    (2, 17),
    (2, 18),
    (3, 1),
    (3, 2),
    (3, 3),
    (3, 4),
    (3, 5),
    (3, 6),
    (3, 7),
    (3, 8),
    (3, 9),
    (3, 10),
    (3, 11),
    (3, 12),
    (3, 13),
    (3, 14),
    (3, 15),
    (3, 16),
    (3, 17),
    (3, 18),
    (4, 1),
    (4, 2),
    (4, 3),
    (4, 4),
    (4, 5),
    (4, 6),
    (4, 7),
    (4, 8),
    (4, 9),
    (4, 10),
    (4, 11),
    (4, 12),
    (4, 13),
    (4, 14),
    (4, 15),
    (4, 16),
    (4, 17),
    (4, 18),
    (5, 1),
    (5, 2),
    (5, 3),
    (5, 4),
    (5, 5),
    (5, 6),
    (5, 7),
    (5, 8),
    (5, 9),
    (5, 10),
    (5, 11),
    (5, 12),
    (5, 13),
    (5, 14),
    (5, 15),
    (5, 16),
    (5, 17),
    (5, 18),
    (6, 1),
    (6, 2),
    (6, 3),
    (6, 4),
    (6, 5),
    (6, 6),
    (6, 7),
    (6, 8),
    (6, 9),
    (6, 10),
    (6, 11),
    (6, 12),
    (6, 13),
    (6, 14),
    (6, 15),
    (6, 16),
    (6, 17),
    (6, 18),
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    (7, 5),
    (7, 6),
    (7, 7),
    (7, 8),
    (7, 9),
    (7, 10),
    (7, 11),
    (7, 12),
    (7, 13),
    (7, 14),
    (7, 15),
    (7, 16),
    (7, 17),
    (7, 18),
    (8, 1),
    (8, 2),
    (8, 3),
    (8, 4),
    (8, 5),
    (8, 6),
    (8, 7),
    (8, 8),
    (8, 9),
    (8, 10),
    (8, 11),
    (8, 12),
    (8, 13),
    (8, 14),
    (8, 15),
    (8, 16),
    (8, 17),
    (8, 18),
    (9, 1),
    (9, 2),
    (9, 3),
    (9, 4),
    (9, 5),
    (9, 6),
    (9, 7),
    (9, 8),
    (9, 9),
    (9, 10),
    (9, 11),
    (9, 12),
    (9, 13),
    (9, 14),
    (9, 15),
    (9, 16),
    (9, 17),
    (9, 18),
    (10, 1),
    (10, 2),
    (10, 3),
    (10, 4),
    (10, 5),
    (10, 6),
    (10, 7),
    (10, 8),
    (10, 9),
    (10, 10),
    (10, 11),
    (10, 12),
    (10, 13),
    (10, 14),
    (10, 15),
    (10, 16),
    (10, 17),
    (10, 18),
    (11, 18),
    (11, 19),
    (11, 20),
    (11, 21),
    (12, 23),
    (14, 24),
    (15, 25),
    (16, 22),
    (17, 22);